import sqlite3

# Establecer la conexión a la base de datos SQLite (se crea si no existe)
conexion = sqlite3.connect('practica_bbdd/mi_bbdd.db')

# Crear un cursor para ejecutar comandos SQL
#creamos una variable cursor que nos permite ejecutar comandos SQL
cursor = conexion.cursor()

#ejecutamos la instrucción sqlite de crear tabla
#Con las columnas y el tipo de dato que va en ellas CTD_ARTICULO, PRECIO, SECCION

#si la tabla ya existe no la crea y salta la excepción
    #Hacemos el código autgenerado AUTOGENERATED
    #cursor.execute("CREATE TABLE PRODUCTOS (CTD_ARTICULO VARCHAR(50), PRECIO REAL, SECCION VARCHAR(20))")

cursor.execute('''
    CREATE TABLE IF NOT EXISTS PRODUCTOS (
        ID INTEGER PRIMARY KEY AUTOINCREMENT,
        ARTICULO VARCHAR(50),
        PRECIO REAL,
        SECCION VARCHAR(20)
    )'''
)
    

#insertar datos en la tabla
#insertamos varios registros a la vez con executemany
cursor.execute("INSERT INTO PRODUCTOS VALUES (NULL,'Lapiz', 0.95, 'Papelería'),"
"(NULL,'Borrador', 0.50, 'Papelería'), (NULL,'Tijeras', 2.35, 'Papelería'),"
"(NULL,'Cinta adhesiva', 1.20, 'Papelería'), (NULL,'Grapadora', 5.75, 'Papelería'),"
"(NULL,'Taladro', 15.00, 'Ferretería'), (NULL,'Clavos', 3.50, 'Ferretería'),"
"(NULL,'Tornillos', 4.00, 'Ferretería')")

#Otra forma de agregar varios datos
lista_productos = [
    ("Patinente", 100, "Deportes"),
    ("Skate", 250.25, "Deportes"),
    ("Floy Mochila", 190, "BagPacks")
]


#Para insertar executemany nos pide un objeto iterable como una lista o una tupla
#se realiza una busqueda parametrizada con ?
cursor.executemany("INSERT INTO PRODUCTOS VALUES (NULL, ?, ?, ?)", lista_productos)

#guardar los cambios
conexion.commit()

#Cerramos el cursor
cursor.close()

#cerrar la conexión
conexion.close()